### ISSUE TITLE
Demo screenshot

### ISSUE THREAD

**Issue by ruchernchong** [wilderborn/partyline#1]
Will be great to have a demo screenshot of how it works. I cannot seem to picture this in my mine.

**Comment by jackmcdade** [comment]
It's a little bit of a strange thing to screenshot because it's basically just letting you move code from inside your Command class to elsewhere in your application. It would look the same on the CLI side. You can see a more robust example on our blog with an animated gif and everything :)

**Comment by cawhite78** [comment]
Non-static method Wilderborn\Partyline\Partyline::bind() should not be called statically.  

Inside my command's handle

`
public function handle()
{
    Partyline::bind($this);
}
`

inside the class called in my handle

`
Partyline::info('syncing partner id: ' . $partnerId );
`

info is a public Illuminate\Console\Command method....

Laravel Framework 5.4.33

**Comment by taytus** [comment]
A very tiny example would be wonderful to have.
I can't make this work after following the installation process.

  Non-static method Wilderborn\Partyline\Partyline::bind() should not be call  
  ed statically

**Comment by jasonvarga** [comment]
You should use `Partyline`, not `Wilderborn\Partyline\Partyline`

**Comment by taytus** [comment]
Thank you @jasonvarga!
