### ISSUE TITLE
Feature request: log lines

### ISSUE THREAD

**Issue by underdpt** [wilderborn/partyline#3]
Hi,

It would be helpful if partyline could log the line to laravel's log (when configured to do so). That way, in one `Partyline::` command we could print the line and save it (when the command isn't run by the user but by a cron task).

It would be neccesary to map partyline function calls to `Log`, so maybe `Partyline::line` would call `Log::info`, `Partyline::info` would call `Log::info` and so on.

**Comment by jasonvarga** [comment]
We'd happily review a PR but have no plans to add this feature.

You could try using the `screen` command as explained here. https://stackoverflow.com/a/56807920/1569621
