### ISSUE TITLE
Non-static method Partyline::bind() cannot be called statically

### ISSUE THREAD

**Issue by raphaelbeckmann** [wilderborn/partyline#7]
Suggestion to update the readme:

Using Laravel 5.5 or higher, you don't need to update your `config/app.php` file.
Hence, writing

```
public function handle()
{
    Partyline::bind($this);
}
```

will result in an error: `Non-static method Partyline::bind() cannot be called statically`

So, instead of importing `Wilderborn\Partyline\Partyline`, you need to import the Facade like this:
`use Wilderborn\Partyline\Facade as Partyline;`

This should be done in both the AbstractCommand and the external class where you are going to write `Partyline::info()` etc.

**Comment by jasonvarga** [comment]
Ah yes, you can either do `\Partyline::bind()` (with the slash) or import the facade. We can update the docs!
