### ISSUE TITLE
IDE auto-discover "newLine" method

### ISSUE THREAD

**Issue by roberto910907** [wilderborn/partyline#8]
It would be good if we could add a new `@method` [here](https://github.com/wilderborn/partyline/blob/master/src/Facade.php#L17) so the **Partyline** facade recognizes the `newLine` method when using IDE auto-completion.

**Comment by jasonvarga** [comment]
I was about to say, before you edited it, that it works just fine.

But sure, we can add it to the docblock.

**Comment by roberto910907** [comment]
@jasonvarga great, thanks! Looking forward to it. BTW, I'm not sure if `ask` is missing from there too.

**Comment by jasonvarga** [comment]
Yeah there's a bunch more we can add. We'll accept a PR if you need this faster.
